### ISSUE TITLE
if (username.equals("login") && password.equals("password")) hardcoding is genius!

### ISSUE THREAD

**Issue by vadim-a-yegorov** [TheLivan/SimpleAuthProvider#1]
It's so good so I can't comment anymore

https://github.com/TheLivan/SimpleAuthProvider/blob/main/src/com/thelivan/auth/Main.java#L44

But I suggest considering connecting to MariaDB or MongoDB just in case:

https://www.javaguides.net/2019/07/login-application-using-java-swing-jdbc-mysql-example-tutorial.html

**Comment by TheLivan** [comment]
This was done on purpose, this is the essence of the project.

This project was used by me in another small project.
The project team consisted of 3-5 people.
I didn't want to use databases and made a temporary solution.

If you do not understand the focus of the project, then I do not think that you need to create an issue for this.
But I am pleased that someone paid attention to this small project. Thank you.
